name: profit_tracker
description: تطبيق flutter عربي لتتبع الأرباح مع حفظ محلي داخل الجهاز ونسخة احتياطية مرتبطة بالبريد الشخصي للمستخدم.
publish_to: 'none'
version: 1.3.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  share_plus: ^7.2.2
  cross_file: ^0.3.4+2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
