name: profit_tracker
description: تطبيق flutter عربي لتتبع الأرباح مع حفظ محلي وسحابي تلقائي عبر firebase ومؤشرات سوق مباشرة مع بدائل يدوية.
publish_to: 'none'
version: 1.5.0+7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  share_plus: ^7.2.2
  http: ^1.2.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/maen_accountings_icon.png
  min_sdk_android: 21
  adaptive_icon_background: '#0B172A'
  adaptive_icon_foreground: assets/icon/maen_accountings_icon.png
