using Maen.Accounting.App.Services;

namespace Maen.Accounting.App;

public static class UiText
{
    public static AppLanguage Language { get; set; } = AppLanguage.Arabic;

    private static readonly Dictionary<string, (string Arabic, string English)> Values = new()
    {
        ["T001"] = ("English", "English"),
        ["T002"] = ("أحدث السجلات", "Recent entries"),
        ["T003"] = ("إجمالي الدائن", "Total credit"),
        ["T004"] = ("إجمالي الفواتير المرحّلة", "Posted invoices total"),
        ["T005"] = ("إجمالي المبيعات", "Total sales"),
        ["T006"] = ("إجمالي المدفوعات", "Total payments"),
        ["T007"] = ("إجمالي المدين", "Total debit"),
        ["T008"] = ("إجمالي المصروفات", "Total expenses"),
        ["T009"] = ("إدخال", "Entry"),
        ["T010"] = ("إضافة سجل جديد", "Add new entry"),
        ["T011"] = ("إنشاء حساب جديد", "Create account"),
        ["T012"] = ("ابدأ بدون تسجيل", "Continue without registration"),
        ["T013"] = ("اختر اللغة", "Choose your language"),
        ["T014"] = ("اختر لغتك وطريقة استخدامك للتطبيق، وسنجهز لك تجربة مناسبة من البداية.", "Choose your language and how you use the app. We will prepare the right experience from the start."),
        ["T015"] = ("اختر نوع الحساب", "Choose your account type"),
        ["T016"] = ("استخدم البريد وكلمة المرور للمزامنة والنسخ الاحتياطي السحابي.", "Use your email and password for cloud sync and backup."),
        ["T017"] = ("استيراد نسخة Flutter أو MAUI", "Import a Flutter or MAUI backup"),
        ["T018"] = ("الإعدادات", "Settings"),
        ["T019"] = ("الإعدادات والنسخ", "Settings & backups"),
        ["T020"] = ("البريد الإلكتروني", "Email"),
        ["T021"] = ("التاريخ", "Date"),
        ["T022"] = ("التقارير", "Reports"),
        ["T023"] = ("الحساب", "Account"),
        ["T024"] = ("الحساب الدائن", "Credit account"),
        ["T025"] = ("الحساب المدين", "Debit account"),
        ["T026"] = ("الحسابات", "Accounts"),
        ["T027"] = ("الحسابات الفردية", "Personal accounts"),
        ["T028"] = ("الخصوصية", "Privacy"),
        ["T029"] = ("الدخول", "Sign in"),
        ["T030"] = ("الدخول السحابي", "Cloud sign in"),
        ["T031"] = ("الدخول محليًا بدون تسجيل", "Local access without registration"),
        ["T032"] = ("الرئيسية", "Home"),
        ["T033"] = ("الربح الإجمالي", "Gross profit"),
        ["T034"] = ("الربح الإجمالي للشهر", "Monthly gross profit"),
        ["T035"] = ("السجل اليومي", "Daily entry"),
        ["T036"] = ("الشركات والمحلات", "Business & shops"),
        ["T037"] = ("العربية", "Arabic"),
        ["T038"] = ("العملاء والموردون والفواتير والمدفوعات", "Customers, suppliers, invoices and payments"),
        ["T039"] = ("العمليات", "Operations"),
        ["T040"] = ("العمليات التجارية", "Business operations"),
        ["T041"] = ("العميل أو المورد", "Customer or supplier"),
        ["T042"] = ("القيود المرحّلة", "Posted journal entries"),
        ["T043"] = ("المبيعات", "Sales"),
        ["T044"] = ("المحاسبة", "Accounting"),
        ["T045"] = ("المزامنة", "Sync"),
        ["T046"] = ("المزامنة تقارن وقت وإصدار كل سجل، ولا تستبدل قاعدة كاملة بقاعدة أقدم.", "Sync compares the time and version of every entry; it never replaces a database with an older one."),
        ["T047"] = ("المشتريات والمصروفات اليومية", "Purchases & daily expenses"),
        ["T048"] = ("المصروفات", "Expenses"),
        ["T049"] = ("النسخة الاحتياطية", "Backup"),
        ["T050"] = ("النوع", "Type"),
        ["T051"] = ("تأكيد كلمة المرور", "Confirm password"),
        ["T052"] = ("تحديث", "Update"),
        ["T053"] = ("ترحيل السجلات القديمة", "Migrate legacy entries"),
        ["T054"] = ("ترحيل القيد", "Post entry"),
        ["T055"] = ("تسجيل الخروج", "Sign out"),
        ["T056"] = ("تسجيل الدخول", "Sign in"),
        ["T057"] = ("تصدير نسخة JSON", "Export JSON backup"),
        ["T058"] = ("تعديل", "Edit"),
        ["T059"] = ("تكلفة القطع", "Cost of goods"),
        ["T060"] = ("حالة الميزان", "Trial balance status"),
        ["T061"] = ("حذف", "Delete"),
        ["T062"] = ("حفظ", "Save"),
        ["T063"] = ("حفظ وترحيل العملية", "Save & post transaction"),
        ["T064"] = ("حفظ وترحيل الفاتورة", "Save & post invoice"),
        ["T065"] = ("دفعة أو قبض جديد", "New payment or receipt"),
        ["T066"] = ("دليل الحسابات", "Chart of accounts"),
        ["T067"] = ("دليل الحسابات وميزان المراجعة والقيود المرحّلة", "Chart of accounts, trial balance and posted entries"),
        ["T068"] = ("سجلات مالية يومية دقيقة مع فصل كامل بين الحسابات", "Accurate daily financial records with complete account isolation"),
        ["T069"] = ("صافي الربح المتوقع", "Expected net profit"),
        ["T070"] = ("صافي السنة", "Year net profit"),
        ["T071"] = ("صافي الشهر", "Month net profit"),
        ["T072"] = ("عدد السجلات", "Entry count"),
        ["T073"] = ("عميل أو مورد جديد", "New customer or supplier"),
        ["T074"] = ("فاتورة جديدة", "New invoice"),
        ["T075"] = ("قيد يومية جديد", "New journal entry"),
        ["T076"] = ("كلمة المرور", "Password"),
        ["T077"] = ("لا توجد حسابات.", "No accounts yet."),
        ["T078"] = ("لا توجد سجلات بعد.", "No entries yet."),
        ["T079"] = ("لا توجد سجلات في هذا الشهر.", "No entries this month."),
        ["T080"] = ("لا توجد فواتير.", "No invoices."),
        ["T081"] = ("لا توجد قيود مرحّلة بعد.", "No posted entries yet."),
        ["T082"] = ("لا توجد مدفوعات.", "No payments."),
        ["T083"] = ("لا يرسل التطبيق عنوان IP لتحديد الموقع، ولا يطلب GPS، ولا يجلب الطقس أو أسعار السوق. الاتصال الخارجي مقتصر على تسجيل الدخول والمزامنة التي يختارها المستخدم.", "The app does not send your IP for location, request GPS, or fetch weather or market prices. External connections are limited to sign-in and user-initiated sync."),
        ["T084"] = ("لا يوجد عملاء أو موردون.", "No customers or suppliers."),
        ["T085"] = ("م", "M"),
        ["T086"] = ("مبيعات الشهر", "Month sales"),
        ["T087"] = ("متابعة", "Continue"),
        ["T088"] = ("متوسط صافي السجل", "Average entry net"),
        ["T089"] = ("مرحباً بك", "Welcome"),
        ["T090"] = ("مركز المحاسبة", "Accounting center"),
        ["T091"] = ("مزامنة الآن", "Sync now"),
        ["T092"] = ("معن للمحاسبة", "Maen Accounting"),
        ["T093"] = ("ملاحظات", "Notes"),
        ["T094"] = ("ملخص مباشر مبني على سجلاتك المحلية الحالية", "A live summary based on your current local entries"),
        ["T095"] = ("ميزان المراجعة", "Trial balance"),
        ["T096"] = ("نسيت كلمة المرور؟", "Forgot password?"),
        ["T097"] = ("نشط", "Active"),
        ["T098"] = ("نظامك المالي، بصورة أوضح", "Your finances, made clearer"),
        ["T099"] = ("نظرة مالية", "Financial overview"),
        ["T100"] = ("نوع العملية", "Transaction type"),
        ["T101"] = ("نوع الفاتورة", "Invoice type"),
        ["T102"] = ("يفتح البرنامج مباشرة دون بريد أو كلمة مرور. تبقى البيانات على هذا الجهاز فقط.", "Opens directly without email or password. Data stays on this device only."),
        ["T103"] = ("يمكنك تغيير هذا الاختيار لاحقاً من الإعدادات.", "You can change this choice later from Settings."),
        ["T104"] = ("يُحفظ سجل واحد لكل تاريخ، وأي تعديل يُسجّل بإصدار جديد للمزامنة الآمنة.", "One entry is kept per date; every edit creates a new version for safe synchronization."),
        ["T105"] = ("محفظتي الشخصية", "My personal wallet"),
        ["T106"] = ("تابع دخلك ومصروفاتك اليومية بصورة أبسط", "Track your daily income and expenses with clarity"),
        ["T107"] = ("رصيد الشهر", "Monthly balance"),
        ["T108"] = ("دخل الشهر", "Monthly income"),
        ["T109"] = ("مصروفات الشهر", "Monthly spending"),
        ["T110"] = ("إضافة حركة مالية", "Add a money record"),
        ["T111"] = ("دخل أو بيع", "Income or sale"),
        ["T112"] = ("شراء أو مصروف", "Purchase or expense"),
        ["T113"] = ("التحويلات والملاحظات", "Transfers & notes"),
        ["T114"] = ("حركة اليوم", "Today's record"),
        ["T115"] = ("تسجل هذه الصفحة يومك المالي: ما دخل إليك وما أنفقته.", "This page records your day: what came in and what you spent."),
        ["T116"] = ("المبلغ الداخل", "Money in"),
        ["T117"] = ("المبلغ المنفق", "Money out"),
        ["T118"] = ("تبديل نوع الحساب", "Change account type"),
        ["T119"] = ("تبديل اللغة", "Change language"),
        ["T120"] = ("تم الحفظ", "Saved"),
        ["T121"] = ("تعذر الحفظ", "Could not save"),
        ["T122"] = ("حسنًا", "OK"),
        ["T123"] = ("التجربة واللغة", "Experience & language"),
        ["T124"] = ("يمكنك إعادة اختيار اللغة ونوع الحساب في أي وقت. لن تُحذف بياناتك الحالية.", "You can choose your language and account type again at any time. Your current data will not be deleted."),
        ["T125"] = ("إعادة الاختيار", "Choose again"),
        ["T126"] = ("حساب سحابي محمي", "Protected cloud account"),
        ["T127"] = ("وضع محلي على هذا الجهاز", "Local mode on this device"),
        ["T128"] = ("حفظ السجل", "Save record"),
        ["T129"] = ("تحديث السجل", "Update record"),
        ["T130"] = ("لم تتم المزامنة بعد", "No sync yet"),
        ["T131"] = ("لا توجد نسخة محلية بعد", "No local backup yet"),
        ["T132"] = ("تم حفظ السجل محلياً.", "Record saved locally."),
        ["T133"] = ("تم الحفظ محلياً وتمت المزامنة السحابية بنجاح — رُفع {0} سجل، وتم التحقق من {1} سجل — {2}.", "Saved locally and cloud sync succeeded — uploaded {0} record(s), verified {1} record(s) — {2}."),
        ["T134"] = ("تم الحفظ محلياً وتمت المزامنة السحابية بنجاح — السجل موجود ومؤكد في السحابة — تم التحقق من {0} سجل — {1}.", "Saved locally and cloud sync succeeded — the record is confirmed in the cloud — verified {0} record(s) — {1}."),
        ["T135"] = ("تم الحفظ محلياً، لكن تعذرت المزامنة. اضغط مزامنة الآن لإعادة المحاولة.", "Saved locally, but cloud sync could not be completed. Tap Sync now to retry."),
        ["T136"] = ("آخر مزامنة سحابية ناجحة: {0} — رُفع {1} سجل — تم التحقق من {2} سجل", "Last successful cloud sync: {0} — uploaded {1} record(s) — verified {2} record(s)"),
        ["T137"] = ("آخر مزامنة سحابية ناجحة: {0} — لا تغييرات معلقة — تم التحقق من {1} سجل", "Last successful cloud sync: {0} — no pending changes — verified {1} record(s)"),
        ["T138"] = ("آخر نسخة: {0} — {1} سجل", "Last backup: {0} — {1} record(s)"),
        ["T139"] = ("حقل «{0}» يحتوي على مبلغ غير صحيح أو سالب.", "The {0} field has an invalid or negative amount."),
        ["T140"] = ("لا توجد جلسة مستخدم نشطة.", "No active user session."),
        ["T141"] = ("لا توجد ملاحظات", "No notes"),
        ["T142"] = ("المزامنة السحابية متاحة للحسابات المسجلة فقط.", "Cloud sync is available for signed-in accounts only."),
        ["T143"] = ("دخل من عمل", "Work income"),
        ["T144"] = ("بيع", "Sale"),
        ["T145"] = ("شراء", "Purchase"),
        ["T146"] = ("مصروف", "Expense"),
        ["T147"] = ("تحويل", "Transfer"),
        ["T148"] = ("أخرى", "Other"),
        ["T149"] = ("المبلغ", "Amount"),
        ["T150"] = ("مال خرج", "Money out"),
        ["T151"] = ("مال دخل", "Money in"),
        ["T152"] = ("نوع الحركة", "Movement type"),
        ["T153"] = ("اتجاه المبلغ", "Money direction"),
        ["T154"] = ("صنّف الحركة لتظهر محفظتك بصورة أوضح.", "Classify the movement to make your wallet clearer."),
        ["T155"] = ("صحة الميزانية هذا الشهر", "This month's money health"),
        ["T156"] = ("الإنفاق من الدخل", "Spending from income"),
        ["T157"] = ("حركات هذا الشهر", "This month's records"),
        ["T158"] = ("إنفاق متوازن — لديك رصيد إيجابي هذا الشهر.", "Balanced spending — you have a positive balance this month."),
        ["T159"] = ("تنبيه: مصروفاتك هذا الشهر أعلى من دخلك.", "Attention: this month's spending is higher than your income."),
        ["T160"] = ("أضف حركة واحدة يومياً لتحصل على ملخص أدق.", "Add one record each day for a clearer summary."),
        ["T161"] = ("لا توجد حركة هذا الشهر بعد.", "No records this month yet."),
        ["T162"] = ("ملخص الشهر", "Monthly snapshot"),
    };

    public static string Get(string key)
    {
        if (!Values.TryGetValue(key, out var value)) return key;
        return Language == AppLanguage.English ? value.English : value.Arabic;
    }

    public static string Format(string key, params object?[] arguments) =>
        string.Format(System.Globalization.CultureInfo.CurrentUICulture, Get(key), arguments);
}
